os:
  - linux
dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.7


services:
  - xvfb



before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - conda config --add channels conda-forge

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - echo $TRAVIS_PYTHON_VERSION
    - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - conda install numpy -y 
    - conda install scipy -y
    - "export DISPLAY=:99.0"
    #- conda install --yes --file requirements.txt
    #- conda install --yes --file requirements-dev.txt
    - pip install .
    - pip install -r requirements-dev.txt 

# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=spectrum --cov-report term --timeout 300 

after_success:
  coveralls
